name: CI Pipeline

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        working-directory: ./django_rest_api
        run: |
          docker-compose up --build -d

      - name: Wait for services to be ready
        working-directory: ./django_rest_api
        run: |
          docker-compose exec -T django bash -c "until nc -z localhost 8000; do sleep 1; done"

      - name: Run Tests
        working-directory: ./django_rest_api
        run: |
          docker-compose exec django pytest --maxfail=5 --disable-warnings -v

      - name: Tear down services
        if: always()
        working-directory: ./django_rest_api
        run: |
          docker-compose down